/**
 * Regression test: a class with two associations to the same target class
 * must not produce duplicate imports in the generated finder.
 *
 * Finders are generated by: uv run python example/generate_dual_assoc.py
 * Schema: Order.billingAccount and Order.shippingAccount both reference Account.
 */
import { describe, it, beforeAll, afterAll, expect } from 'vitest';
import { DuckDBInstance, DuckDBConnection } from '@duckdb/node-api';
import { registerDuckDb } from './duckdb-runner';

let conn: DuckDBConnection;
let instance: DuckDBInstance;

async function run(sql: string): Promise<void> {
  await conn.run(sql);
}

beforeAll(async () => {
  instance = await DuckDBInstance.create(':memory:');
  conn = await instance.connect();
  registerDuckDb(conn);

  await run('CREATE SCHEMA shop');
  await run('CREATE TABLE shop.account(ID INT, NAME VARCHAR)');
  await run("INSERT INTO shop.account VALUES (1, 'Billing Co')");
  await run("INSERT INTO shop.account VALUES (2, 'Shipping Co')");
  await run('CREATE TABLE shop.order_(ID INT, BILLING_ACCOUNT_ID INT, SHIPPING_ACCOUNT_ID INT)');
  await run("INSERT INTO shop.order_ VALUES (42, 1, 2)");
});

afterAll(() => {
  conn.disconnectSync();
  instance.closeSync();
});

describe('OrderFinder — dual association to Account', () => {
  it('resolves billingAccount name', async () => {
    const { OrderFinder } = await import('./generated_dual_assoc/OrderFinder');
    const of_ = new OrderFinder();

    const rows = await of_.findAll(null, null,
      [of_.id(), of_.billingAccount().name()],
      of_.id().eq(42),
    ).toRows();

    expect(rows.length).toBe(1);
    expect(rows[0][1]).toBe('Billing Co');
  });

  it('resolves shippingAccount name', async () => {
    const { OrderFinder } = await import('./generated_dual_assoc/OrderFinder');
    const of_ = new OrderFinder();

    const rows = await of_.findAll(null, null,
      [of_.id(), of_.shippingAccount().name()],
      of_.id().eq(42),
    ).toRows();

    expect(rows.length).toBe(1);
    expect(rows[0][1]).toBe('Shipping Co');
  });

  it('resolves both accounts in the same query', async () => {
    const { OrderFinder } = await import('./generated_dual_assoc/OrderFinder');
    const of_ = new OrderFinder();

    const rows = await of_.findAll(null, null,
      [of_.id(), of_.billingAccount().name(), of_.shippingAccount().name()],
      of_.id().eq(42),
    ).toRows();

    expect(rows.length).toBe(1);
    expect(rows[0][1]).toBe('Billing Co');
    expect(rows[0][2]).toBe('Shipping Co');
  });

  it('SQL contains two separate LEFT OUTER JOINs to the same table', async () => {
    const { OrderFinder } = await import('./generated_dual_assoc/OrderFinder');
    const of_ = new OrderFinder();

    const sql = of_.findAll(null, null,
      [of_.billingAccount().name(), of_.shippingAccount().name()],
    ).toSql();

    const joinCount = (sql.match(/LEFT OUTER JOIN/g) ?? []).length;
    expect(joinCount).toBe(2);
  });
});
